#!/bin/sh

selection=$(cat ~/.local/bin/emoji | wofi -d -p emoji -l 15 | awk '{print $1}' &)
[[ -z $selection ]] && notify-send ":( Nothing Entered" && exit 1
printf "$selection" | wl-copy && notify-send "$selection copied to clipboard!" && exit 0
