theme = "gruvbox_dark_hard"

[editor]
line-number = "relative"
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "version-control", "file-name", "diagnostics", "spinner"]
center = ["spacer"]
right = ["position", "separator", "file-encoding", "file-line-ending", "separator", "total-line-numbers"]
separator = "::"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
